export default {
  // Recipes
  SET_SEARCHED_RECIPES: 'SET_SEARCHED_RECIPES',

  // Navigation
  NAVIGATION_FORWARD: 'NAVIGATION_FORWARD',
  NAVIGATION_BACK: 'NAVIGATION_BACK',
  SET_TAB: 'SET_TAB'
}

